UGID='220000'
MEMORY='2G'
CPU_SHARES='1024'

source "${SCRIPTDIR}/../_misc/variables.sh"

CONFIGPATH="${HOSTPATH}/config"
LIBPATH="${HOSTPATH}/lib"
LOGPATH="${HOSTPATH}/log"
RUNPATH="${HOSTPATH}/run"
TMPPATH="${HOSTPATH}/tmp"
