UGID='110000'
MEMORY='4G'
CPU_SHARES='1024'

source "${SCRIPTDIR}/../_misc/variables.sh"

CONFIGPATH="${HOSTPATH}/config"
LIBPATH="${HOSTPATH}/lib"
LOGPATH="${HOSTPATH}/log"
PLUGINPATH="${HOSTPATH}/plugins"
TMPPATH="${HOSTPATH}/tmp"
