UGID='250000'
PRIMPATH='/exim'
MEMORY='2G'
CPU_SHARES='1024'

source "${SCRIPTDIR}/../_misc/variables.sh"

CONFIGPATH="${HOSTPATH}/config"
CRYPTOPATH="${HOSTPATH}/crypto"
LOGPATH="${HOSTPATH}/log"
SPOOLPATH="${HOSTPATH}/spool"
