UGID='190000'
MEMORY='2G'
CPU_SHARES='512'

source "${SCRIPTDIR}/../_misc/variables.sh"

CONFIGPATH="${HOSTPATH}/config"
LIBPATH="${HOSTPATH}/lib"
LOGPATH="${HOSTPATH}/log"
TMPPATH="${HOSTPATH}/tmp"
TUNPATH="${HOSTPATH}/tun"
