UGID='160000'
PRIMPATH='/nginx'
MEMORY='2G'
CPU_SHARES='512'

source "${SCRIPTDIR}/../_misc/variables.sh"

CONFIGPATH="${HOSTPATH}/config"
CRYPTOPATH="${HOSTPATH}/crypto"
LIBPATH="${HOSTPATH}/lib"
LOGPATH="${HOSTPATH}/log"
