BNAME='builder'
UGID='99999'
PRIMPATH='/builder'
MEMORY='4G'
CPU_SHARES='256'

source "${SCRIPTDIR}/../_misc/variables.sh"
HOSTPATH="${SRVPATH}/${BNAME}"

CONFIGPATH="${HOSTPATH}/config"
GNUPGHOME="${HOSTPATH}/gnupg"
LOGPATH="${HOSTPATH}/log"
PKGBUILDPATH="${HOSTPATH}/pkgbuild"
PKGCACHEPATH="${HOSTPATH}/pkgcache"
PKGPATH="${HOSTPATH}/pkg"
SRCPATH="${HOSTPATH}/src"
